version: '3.8'

services:
  my-node-app:
    build: .
    container_name: web_trainer_app
    restart: always
    network_mode: host
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      - PORT=3000
    volumes:
      - ./data:/app/data:z